language: java
env:
  global:
  - TERM=dumb
cache:
  directories:
    - $HOME/.m2
before_install:
 - cd egov
jdk:
  - oraclejdk8
services:
  - postgresql
addons:
  postgresql: "9.4"
install: travis_wait 60 mvn clean package -q -V -B -s settings.xml -DskipTests -Dmaven.javadoc.skip=true -Ddb.url=jdbc:postgresql://localhost:5432/travis -Ddb.password= -Ddb.user=postgres -Ddb.driver=org.postgresql.Driver -Dbuild.number=1
